Resources:
  eventsEC2:
    Type: AWS::EC2::Instance
    DependsOn: rdsDBInstance
    Properties: 
      KeyName: andrea-juanma-urjc
      ImageId: !Ref AmiId
      InstanceType: "t2.micro"
      SecurityGroups:
        - !Ref httpsSecurityGroup
      IamInstanceProfile: !Ref ec2InstanceProfile
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
              #!/bin/bash -ex
              apt-get update && sudo apt install -y openjdk-11-jdk
              wget ${URLDownloadJar}
              java -DBUCKET_NAME=${BucketName} -DRDS_ENDPOINT=database-events.cjyvoxj9hemh.us-east-1.rds.amazonaws.com -DRDS_DATABASE=events -DRDS_USER=admin -DRDS_PASS=${DBPassword} -Dspring.profiles.active=production -jar app.jar
  eventsS3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
  httpsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: httpsSecurityGroup
      GroupDescription: "SG for EC2 with 80, 433 and 8443 ports"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8443'
          ToPort: '8443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  rdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: rdsSecurityGroup
      GroupDescription: "SG for MYSQL with 3306"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          SourceSecurityGroupName: !Ref httpsSecurityGroup # Sólo permite acceso a las instancias de este grupo -> a la EC2
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: "db.t2.micro"
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DBInstanceIdentifier: events
      DBName: events
      Engine: mysql
      EngineVersion: 8.0
      MasterUsername: events
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
      VPCSecurityGroups:
        - !GetAtt rdsSecurityGroup.GroupId
  ec2S3FullAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
  ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles: 
        - !Ref ec2S3FullAccessRole
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: AWSJS
Parameters:
  DBPassword:
    Type: String 
    Description: The password of the database
  BucketName:
    Type: String 
    Description: The name of the bucket
    Default: andrea-juanma-urjc
    # TODO: Mirar como escapar el guion.
    # AllowedPattern: '^[a-z0-9]{5,40}$'
    # ConstraintDescription: Must contain only lowercase letters or numbers.
  AmiId:
    Type: 'AWS::EC2::Image::Id'
    Description: The ami to use (it must be an AMI on the current region and must be Ubuntu 20.04)
    Default: ami-013f17f36f8b1fefb
  URLDownloadJar:
    Type: String 
    Description: The name of the bucket
    Default: https://s3.amazonaws.com/practica-2.cloud.michel/app.jar



